repos:
-   repo: https://github.com/ambv/black
    rev: 23.10.1
    hooks:
    - id: black
      args: [--safe]
      language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    - id: check-added-large-files
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: debug-statements
    - id: name-tests-test
    - id: requirements-txt-fixer
    - id: flake8
      args: ['--max-line-length=88', '--select=W291,W292,W293,F401']
      language_version: python3
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        exclude: tests
        args:
          - --convention=google
          - --add-ignore=D100,D104,D212,D200,D415
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    - id: mypy
      exclude: tests
      args: ["--ignore-missing-imports", "--implicit-optional", "--follow-imports=skip"]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
      args: ["--profile", "black"]
-   repo: https://github.com/rubik/xenon
    rev: v0.9.0
    hooks:
    - id: xenon
      args: [ --max-absolute A, --max-modules A, --max-average A ]